---
abstract: 'Check file attributes'
author:
  - 'brian d foy <bdfoy@cpan.org>'
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
keywords:
  - testing
  - file
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-File
no_index:
  directory:
    - t/inc
    - inc
  file:
    - t/lib/test.pm
  namespace:
    - Local
  package:
    - version
    - Local
resources:
  repository: git://github.com/briandfoy/test-file.git
version: 1.34_01
