---
abstract: 'Check file attributes'
author:
  - 'brian d foy <bdfoy@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.86, CPAN::Meta::Converter version 2.120921'
keywords:
  - testing
  - file
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-File
no_index:
  directory:
    - t/inc
    - inc
  file:
    - t/lib/test.pm
  namespace:
    - Local
  package:
    - version
    - Local
requires:
  Test::Builder: 1.001006
  Test::Builder::Tester: 1.04
  Test::More: 0.95
  Test::utf8: 0
resources:
  repository: git://github.com/briandfoy/test-file.git
version: 1.40
