# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-File
version:      1.17
version_from: lib/File.pm
installdirs:  site
requires:
    Test::Builder:                 0.33
    Test::Builder::Tester:         1.04
    Test::More:                    0.65

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
